## Import library

In [37]:
import pandas as pd
import joblib
import requests

## Read dataset

In [38]:
data = pd.read_csv("../data/raw/10K_Lending_Club_Loans.csv", encoding='ISO-8859-1')
feature = joblib.load("../data/artifacts/feature_use.pkl")

print(data.shape)
data.head(5)

(10000, 34)

,loan_amnt,funded_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,...,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,mths_since_last_major_derog,policy_code,is_bad
0,4000,4000,60 months,7.29%,79.76,A,A4,Time Warner Cable,10+ years,MORTGAGE,...,NaN,15.0,0.0,12087,12.1,44.0,f,NaN,1,0
1,16000,16000,60 months,18.25%,408.48,F,F1,Ottawa University,< 1 year,RENT,...,NaN,4.0,0.0,10114,64.0,5.0,f,NaN,1,0
2,8700,8700,36 months,7.88%,272.15,A,A5,Kennedy Wilson,4 years,RENT,...,NaN,4.0,0.0,81,0.6,8.0,f,NaN,1,0
3,18000,18000,60 months,11.49%,395.78,B,B4,TOWN OF PLATTEKILL,10+ years,MORTGAGE,...,NaN,6.0,0.0,10030,37.1,23.0,f,NaN,1,0
4,16000,16000,36 months,11.83%,530.15,B,B3,Belmont Correctional,10+ years,MORTGAGE,...,NaN,8.0,0.0,10740,40.4,21.0,f,NaN,1,0

In [39]:
result = pd.read_csv("/Users/phupha/Documents/GitHub/credit-score/data/predicted/data10K_Lending_Club_Loans_predicted.csv")

result.head(5)

,loan_amnt,term,int_rate,grade,annual_inc,verification_status,purpose,inq_last_6mths,revol_util,total_acc,is_bad,loan_amnt_per_installment,income_to_interest_ratio,prediction
0,4000,60 months,0.0729,A,50000.0,not verified,medical,0.0,12.1,44.0,0,50.150451,12.500000,0.095670
1,16000,60 months,0.1825,F,39216.0,not verified,debt_consolidation,2.0,64.0,5.0,0,39.169604,2.451000,0.372553
2,8700,36 months,0.0788,A,65000.0,not verified,credit_card,0.0,0.6,8.0,0,31.967665,7.471264,0.032019
3,18000,60 months,0.1149,B,57500.0,not verified,debt_consolidation,0.0,37.1,23.0,0,45.479812,3.194444,0.145895
4,16000,36 months,0.1183,B,50004.0,VERIFIED - income,debt_consolidation,4.0,40.4,21.0,0,30.180138,3.125250,0.125060

## Sample 1

In [40]:
test = data.iloc[[0],:]
test = test[['loan_amnt', 'term', 'int_rate', 'grade', 'annual_inc',
       'verification_status', 'purpose', 'inq_last_6mths', 'revol_util',
       'total_acc','installment']]
test = test.to_dict(orient="records")
payload = {"data":test}

print(type(payload))
display(payload)

<class 'dict'>

{'data': [{'loan_amnt': 4000,
   'term': ' 60 months',
   'int_rate': '7.29%',
   'grade': 'A',
   'annual_inc': 50000.0,
   'verification_status': 'not verified',
   'purpose': 'medical',
   'inq_last_6mths': 0.0,
   'revol_util': 12.1,
   'total_acc': 44.0,
   'installment': 79.76}]}

In [41]:
url = "http://127.0.0.1:8000/score"

response = requests.post(url, json=payload)

print("Status:", response.status_code)
print("Prediction:", response.json())

Status: 200
Prediction: {'scores': [0.09566960804156632]}

## Sample 2

In [42]:
test = data.iloc[[1],:]
test = test[['loan_amnt', 'term', 'int_rate', 'grade', 'annual_inc',
       'verification_status', 'purpose', 'inq_last_6mths', 'revol_util',
       'total_acc','installment']]
test = test.to_dict(orient="records")
payload = {"data":test}

print(type(payload))
display(payload)

<class 'dict'>

{'data': [{'loan_amnt': 16000,
   'term': ' 60 months',
   'int_rate': '18.25%',
   'grade': 'F',
   'annual_inc': 39216.0,
   'verification_status': 'not verified',
   'purpose': 'debt_consolidation',
   'inq_last_6mths': 2.0,
   'revol_util': 64.0,
   'total_acc': 5.0,
   'installment': 408.48}]}

In [43]:
url = "http://127.0.0.1:8000/score"

response = requests.post(url, json=payload)

print("Status:", response.status_code)
print("Prediction:", response.json())

Status: 200
Prediction: {'scores': [0.37255335141152185]}

---